Repository pagopa/io-infrastructure-live-new, pull requests merged in 2021-04, with the labels that each got.

#492 [#IP-44] add RETRY_ATTEMPT_NUMBER, APPINSIGHTS_SAMPLING_PERCENTAGE variables
  prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl
  prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
Labels: status: applied

#494 [IOINFRA-57] Disable diagnostic settings appbackend
  prod/westeurope/linux/appbackendl1/monitor/analytics/terragrunt.hcl
  prod/westeurope/linux/appbackendl2/monitor/analytics/terragrunt.hcl
  prod/westeurope/linux/appbackendli/monitor/analytics/terragrunt.hcl
Labels: status: applied

#493 [IOPAY-95] Update cors policy to handle _issuer_ in 3ds2 flow
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/policy.xml
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/swagger.json.tmpl
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/terragrunt.hcl
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/post_transactions_challenge3ds2_policy/policy.xml
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/post_transactions_challenge3ds2_policy/terragrunt.hcl
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/post_transactions_method3ds2_policy/policy.xml
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/post_transactions_method3ds2_policy/terragrunt.hcl
Labels: status: applied

#496 [#ENTE-29] Disable UpdateVisibleServicesCache on fn3-admin
  prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl
  prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
Labels: no merge, status: applied

#499 [#IOINFRA-65] Dns record 2dn read replica db support
  prod/westeurope/support/functions_backoffice/function_app/terragrunt.hcl
  prod/westeurope/support/private_dns_zone/zone/terragrunt.hcl
Labels: status: applied

#498 [IP-143] Add new storage account and env variables for FF
  prod/westeurope/internal/api/storage_beta_test_users/account/terragrunt.hcl
  prod/westeurope/internal/api/storage_beta_test_users/table_notification_hub/terragrunt.hcl
  prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl
  prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
Labels: status: applied

#501 [IP-147] Added 4 sandbox NH for enabling partition tests
  prod/westeurope/notifications/sandbox/notification_hub-partition-1/terragrunt.hcl
Labels: status: applied

#503 [IOPAY-111] Add apim config to support xpay flow
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/swagger.json.tmpl
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/get_transactions_xpay_policy/policy.xml
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/get_transactions_xpay_policy/terragrunt.hcl
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/get_transactions_xpay_verification_policy/policy.xml
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/get_transactions_xpay_verification_policy/terragrunt.hcl
Labels: status: apply in progress

#507 [IOPAY-97] Add new env for recaptcha secret - pay portal
  prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl
  prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
Labels: status: applied

#510 [IOPAY-151] Rewrite http to https for io-pay
  prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
Labels: status: apply in progress

#511 [IOPAY-151] Enable HTTP Strict Transport Security (HSTS) Policy for io-pay
  prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
Labels: status: applied

#509 [#IO-ENTE67] Add new io-fn-services-cache
  prod/westeurope/internal/api/functions_servicescache_r3/function_app/terragrunt.hcl
  prod/westeurope/internal/api/functions_servicescache_r3/function_app_slot_staging/terragrunt.hcl
  prod/westeurope/internal/api/functions_servicescache_r3/subnet/terragrunt.hcl
  prod/westeurope/internal/api/functions_servicescache_r3/web_test/terragrunt.hcl
Labels: status: applied

#506 [IOPAY-111] New env to support xpay redirect to io-pay
  prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl
  prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
Labels: status: apply in progress

#463 [#CGN-3] Apim api for cgn merchant function
  prod/westeurope/internal/api/apim/api_management/terragrunt.hcl
  prod/westeurope/internal/api/apim/api_management_api_cgn_merchant/policy.xml
  prod/westeurope/internal/api/apim/api_management_api_cgn_merchant/swagger.json.tmpl
  prod/westeurope/internal/api/apim/api_management_api_cgn_merchant/terragrunt.hcl
Labels: status: applied

#515 [IOPAY-173] Update checkout.pagopa.gov.it origin
  prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/policy.xml
  prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl
  prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
Labels: status: applied

#513 [IP-146] Create new Notification Hubs for partitioning
  prod/westeurope/common/notification_hub_partition_1/terragrunt.hcl
  prod/westeurope/common/notification_hub_partition_2/terragrunt.hcl
  prod/westeurope/common/notification_hub_partition_3/terragrunt.hcl
  prod/westeurope/common/notification_hub_partition_4/terragrunt.hcl
Labels: status: applied

#517 [IP-146] Add env variable to prod and staging
  prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl
  prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
Labels: status: applied

#519 Fix fn-services-cache webtest
  prod/westeurope/internal/api/functions_servicescache_r3/web_test/terragrunt.hcl
Labels: status: applied

#502 [IOPAY-135] Add custom domains for iopayportal
  prod/westeurope/common/cdn/cdn_endpoint_iopay_custom_domain/terragrunt.hcl
Labels: status: applied

#520 [#IOINFRA-73] Reduce cosmos RU
  prod/westeurope/internal/api/cosmosdb/container_sender-services/terragrunt.hcl
  prod/westeurope/internal/api/cosmosdb/container_services/terragrunt.hcl
Labels: status: applied
